#server stuff
server:
  port: 8080
  context-path: /photo_share


#database
params:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/photo_share?zeroDateTimeBehavior=convertToNull&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    connectionTimeout: 600000
    username: root
    password: root
    maximumPoolSize: 15
    initialize: true

spring.datasource.separator: ^;

#files
images:
  rootPath: D:/photo_share/images
  users:
    logo:
      rootPath: /users/logos
      url: /users/logos
    contest:
      rootPath: /users/contests
      url: /users/contests
  contests:
    logo:
      rootPath: /contests/logos
      url: /contests/logos

#experience parameters
experience:
  growingRatio: 5 # $growingRation * nr_of_won_contets = experience
