CREATE TABLE IF NOT EXISTS accounts(
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(70) NOT NULL,
    password BINARY(60) NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)^;

CREATE TABLE IF NOT EXISTS authentication_tokens(
    id INT PRIMARY KEY AUTO_INCREMENT,
    account_id INT NOT NULL ,
    token VARCHAR(50) NOT NULL,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
)^;

CREATE TABLE IF NOT EXISTS users(
    id INT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(75) NOT NULL,
    name VARCHAR(60),
    birthday DATE,
    gender ENUM('MALE', 'FEMALE'),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)^;

CREATE TABLE IF NOT EXISTS user_uploads(
    id INT PRIMARY KEY AUTO_INCREMENT,
    upload_name VARCHAR(100) NOT NULL,
    mime_type ENUM('JPEG', 'JPG', 'PNG', 'GIF'),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)^;

CREATE TABLE IF NOT EXISTS collections(
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    public BIT NOT NULL DEFAULT 0,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)^;